const Asset = require('./models/asset')
const Transaction = require('./models/transaction')
const PortfolioEntry = require('./models/portfolio_entry')
const Wallet = require('./models/wallet')
const Investor = require('./models/investor')

samed = new Investor('Samed', 'samed@tutanota.com', 'pwd')
samed.addWallet('Short Term')
usd = new Asset('US Dollar', 'USD', Asset.types.CURRENCY)
btc = new Asset('Bitcoin', 'BTC', Asset.types.COIN)

shortTermWallet = samed.getWallet('Short Term')
shortTermWallet.addAsset(usd, 1000.0, 1.0)
shortTermWallet.addAsset(btc, 0.4, 45000)
shortTermWallet.buyAsset(btc, 1, 50000)
shortTermWallet.removeAsset(btc, 48500, true)
console.log(shortTermWallet)