@startuml ClassDiagram

class Investor <entity>{
    + name: String
    + email: String
    - password: String
    + wallets: [Wallet]
    + favorites: [Asset]
    + totalValue ()
    + totalPNL ()
    + addFavorite ()
    + removeFavorite ()
    + addWallet (name)
    + getWallet (name)
}

class Wallet <entity> {
    + name: String
    + assets: [OwnedAsset]
    + transactions: [Transaction]
    + totalPNL ()
    + totalValue ()
    + addOwnedAsset (asset, amount, price)
    + buyOwnedAsset (asset, amount, price)
    + sellOwnedAsset (asset, amount, price)
    + removeOwnedAsset (asset, amount, price)
}

class Asset <entity> {
    + symbol: String
    + name: String
    + type: String
}

class PortfolioItem <assetObject> {
    + asset: Asset
    + amount: Number
    - boughtAmount: Number
    + avgBuyPrice: Number
    + transactions: [Transaction]
    + value (price)
    + unrealizedPNL (price)
    + totalPNL ()
}

class Transaction <transactionObject> {
    + time: Number / Datetime
    + asset: Asset
    + type: Type
    + amount: Number
    + price: Number
    + PNL: Number
}

enum AssetType <enum> {
    COIN
    TOKEN
    CURRENCY
}

enum TransactionType <enum> {
    ADD
    REMOVE
    BUY
    SELL
}

Wallet "n" <-UP-* "1" Investor: owns <
Asset <|-- PortfolioItem
PortfolioItem "1" o--> "n" Transaction: has >
Wallet "1" o--> "n" Transaction: has >
Wallet "1" o--> "n" PortfolioItem: has >
Asset  --> "1" AssetType
Transaction --> "1" TransactionType
Investor "1" --> "n" Asset


@enduml